---

- name: Configure limits
  template: src=limits.conf.j2 dest={{limits_path}} owner=root group=root mode=0644

- name: Update sysctl
  sysctl: name={{item.name}} value={{item.value}}
  with_items:  limits_sysctl

- name: Update hosts.allow
  template: src=hosts.allow.j2 dest=/etc/hosts.allow

- name: Update hosts.deny
  template: src=hosts.deny.j2 dest=/etc/hosts.deny
